 <!-- /.content-wrapper -->
  
  <footer class="main-footer">
    <strong>Copyright &copy; 2020-<?php echo date("Y"); ?> <a href="#">HMS</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 2020.12.01
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="/plugins/chart.js/Chart.min.js"></script>
<script src="/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/plugins/moment/moment.min.js"></script>
<script src="/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="/assets/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/assets/js/demo.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/assets/js/pages/dashboard.js"></script>
<!-- DataTables -->
<script src="/plugins/datatables/jquery.dataTables.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<!-- SweetAlert2 -->
<script src="/plugins/sweetalert2/sweetalert2.min.js"></script>

<!-- page script -->
<script>

   
  $(function () {
    $('#PostingTable').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      
    });
  });
  
  $(function() {
    const Toast = Swal.mixin({
      toast: true,
      position: 'top-end',
      showConfirmButton: false,
      timer: 3000
    });

    $('.swalDefaultSuccess').click(function() {
      Toast.fire({
        type: 'success',
        title: 'Job has been posted'
      })
    });
    
  });

</script>


<!-- Nel Inserted -->
<script>
  var ctx = document.getElementById("myChart").getContext('2d');
  var myChart = new Chart(ctx, {
  type: 'bar',
  data: {
  labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
  datasets: [{
  label: '# of Votes',
  data: [12, 19, 3, 5, 2, 3],
  backgroundColor: [
  'rgba(255, 99, 132, 0.2)',
  'rgba(54, 162, 235, 0.2)',
  'rgba(255, 206, 86, 0.2)',
  'rgba(75, 192, 192, 0.2)',
  'rgba(153, 102, 255, 0.2)',
  'rgba(255, 159, 64, 0.2)'
  ],
  borderColor: [
  'rgba(255,99,132,1)',
  'rgba(54, 162, 235, 1)',
  'rgba(255, 206, 86, 1)',
  'rgba(75, 192, 192, 1)',
  'rgba(153, 102, 255, 1)',
  'rgba(255, 159, 64, 1)'
  ],
  borderWidth: 1
  }]
  },
  options: {
  scales: {
  yAxes: [{
  ticks: {
  beginAtZero: true
  }
  }]
  }
  }
  });
</script>
<script>
  $(document).ready(function() {
    $('#example').DataTable();
} );

    var drugIds = [];
    var quantities = [];
    var names = [];
    var amounts = [];
    totals = 0;
    $(document).ready(function() {
      var count = <?php echo $count; ?>; 
      for(var x = 0;x != count; x++){
        $("#selector"+x).click(function() {
          var quantity = parseFloat($("#quantity").val());
          if(!isNaN(quantity) && quantity > 0){
          document.getElementById("addToReceipt").removeAttribute("disabled");
          $("#selection").empty();
          var url_string = window.location.href;
          var url = new URL(url_string);
          var quantity = parseFloat($("#quantity").val());
          var id = url.searchParams.get("id");
          $("#selection").load("selection.php",{
            newId : id,
            quantity : quantity
          });   
          document.getElementById('quantity').value = '';
          $("#quantityWarning").text("");
        }else{
            $("#quantityWarning").text("Required!");
            document.getElementById("quantity").focus();
          }
        });
      }
    });

    function addGetParameter(id){
      window.history.replaceState(null, null, "?id="+id);
    }


    $(document).ready(function() {
      $("#addToReceipt").click(function() {
        var name = $("#drug_name").text();
        var amount = parseFloat($("#drug_amount").text());
        var quantity = parseFloat($("#drug_quantity").text());
          quantities.push(quantity);
          names.push(name);
          amounts.push(amount);
          var url_string = window.location.href;
          var url = new URL(url_string);
          var id = url.searchParams.get("id");
          drugIds.push(id);
          totals += amount;
          $("#total").text(totals.toFixed(2));
          $("#cart").append("<div class='row'><div class='col'>"+quantity+"</div><div class='col'>"+name+"</div><div class='col'>"+amount.toFixed(2)+"</div></div>");
          document.getElementById("submit").removeAttribute("disabled");
      });
    });


    $(document).ready(function(){
      $("#submit").click(function(){
        if(confirm("Are you sure?")){
          var cash = parseFloat($("#cash").val());
          $("#message").load("order.php",{
            names : names,
            quantities : quantities,
            drugIds : drugIds,
            cash : cash,
            amounts : amounts
          });
          document.getElementById("submit").disabled = true;
          document.getElementById("addToReceipt").disabled = true;
        } 
      });
    });

</script>

<!-- Marjon Homis Graph -->
<script>
var ctx = document.getElementById("homisChart").getContext('2d');
var homisChart = new Chart(ctx, {
type: 'line',
data: {
labels: [
  "Drugs", "Stocks", "Transactions", "Payments"],
datasets: [{
data: [
  <?php
    $totalDrugs = $this->view_data['dataRecords2'];
      echo $totalDrugs[0][0];
  ?>,
  <?php
    $totalStocksDrugs = $this->view_data['dataRecords3'];
      echo $totalStocksDrugs[0][0];
  ?>, 
  <?php
    $totaTransactions = $this->view_data['dataRecords4'];
      echo $totaTransactions[0][0];
  ?>, 
  <?php
    $totalPayments = $this->view_data['dataRecords5'];
      echo $totalPayments[0][0];
  ?>
  ],
backgroundColor: [
'rgba(255, 99, 132, 0)',
'rgba(54, 162, 235, 0)',
'rgba(255, 206, 86, 0)',
'rgba(75, 192, 192, 0)'
],
borderColor: [
'rgba(255,99,132,1)',
'rgba(54, 162, 235, 1)',
'rgba(255, 206, 86, 1)',
'rgba(75, 192, 192, 1)' 
],
borderWidth: 1
}]
},
options: {
scales: {
yAxes: [{
ticks: {
beginAtZero: true
}
}]
}
}
});
</script>
</body>
</html>
