<?php
  $active = $this->getAction();
?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="/assets/img/icon.ico" type="image/x-icon">
  <title><?php echo (isset($this->page_title) ? $this->page_title : 'Home') ?></title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- JQVMap -->
  <link rel="stylesheet" href="/plugins/jqvmap/jqvmap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/assets/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="/plugins/daterangepicker/daterangepicker.css">
  <!-- summernote -->
  <link rel="stylesheet" href="/plugins/summernote/summernote-bs4.min.css">
   <!-- DataTables -->
  <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
  <!-- SweetAlert2 -->
  <link rel="stylesheet" href="/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">

  <!-- Navigation Bar -->
  <div class="wrapper">

  <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
      </ul>


      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">

        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-bell"></i>
            <span class="badge badge-warning navbar-badge">15</span>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <span class="dropdown-item dropdown-header">15 Notifications</span>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">
              <i class="fas fa-envelope mr-2"></i> 4 new messages
              <span class="float-right text-muted text-sm">3 mins</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">
              <i class="fas fa-users mr-2"></i> 8 friend requests
              <span class="float-right text-muted text-sm">12 hours</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">
              <i class="fas fa-file mr-2"></i> 3 new reports
              <span class="float-right text-muted text-sm">2 days</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
          </div>
        </li>

        <!-- Logout Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-user"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <a href="#" class="dropdown-item">
              <!-- Message Start -->
              <div class="media">
                <img src="/assets/img/user2-160x160.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                <div class="media-body">
                  <h3 class="dropdown-item-title">
                    User
                    <span class="float-right text-sm text-success"><i class="fas fa-user"></i></span>
                  </h3>
                  <p class="text-sm">Position</p>
                  <div class="dropdown-divider"></div>
                  <p class="text-sm"><button type="button" class="btn btn-block btn-success btn-xs" href="" onclick="window.location.href='/hms';"><i class="fa fa-sign-out-alt"></i> Logout</button></p>
                </div>
              </div>
              <!-- Message End -->
            </a>
            
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->
  </div>
    

    <!-- Side Bar -->
    
<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="/assets/img/AdminLTELogo.png" alt="HMS Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Hospital System</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/assets/img/onel.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Ronel Ocampo</a>
        </div>
      </div>

      

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->


         
          <li class="nav-header">Hospital Core Transaction 3</li>

          <!-- Start Marjon -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-fw fa-tachometer-alt"></i>
              <p>
                Homis
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
    
              <li class="nav-item">
                <a href="/homis/dashboard" class="nav-link"><!-- Link -->
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link"> <!-- Link -->
                  <i class="far fa-circle nav-icon"></i>
                  <p>Title 2</p>
                </a>
              </li>
            </ul>
          </li>
          <!-- End Marjon -->

          <!-- Start Rhonz -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-fw fa-file-prescription"></i>
              <p>
                Medical Package
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="/medPackage/medCreatePackage" class="nav-link"> <!-- Link -->
                  <i class="far fa-circle nav-icon"></i>
                  <p>Create Package</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/medPackage/medPackageList" class="nav-link"><!-- Link -->
                  <i class="far fa-circle nav-icon"></i>
                  <p>Package List</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/medPackage/medPackageAvailList" class="nav-link"> <!-- Link -->
                  <i class="far fa-circle nav-icon"></i>
                  <p>Avail Package List</p>
                </a>
              </li>
            </ul>
          </li>
          <!-- End Rhonz -->

          <!-- Start Ronel -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-fw fa-file-prescription"></i>
              <p>
                Pharmacy
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
    
              <li class="nav-item">
                <a href="/pharmacy/index" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>List of Drugs</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/pharmacy/transaction" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Pharmacy Transaction</p>
                </a>
              </li>
            </ul>
          </li>
          <!-- End Ronel -->
          
          
          <li class="nav-header">My Account</li>
          
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-user"></i>
              <p>
                My Certificates
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="pages/mailbox/mailbox.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View my certificates</p>
                </a>
              </li>
            </ul>
          </li>
          
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-user"></i>
              <p>
                My information
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="pages/mailbox/mailbox.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View my info</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/mailbox/mailbox.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Employee's Manual</p>
                </a>
              </li>
            </ul>
          </li>
          

          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>