<?php include VIEW . 'header.phtml'; ?>

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">

            <!--- Title to ng page na pinasok niyo -->
            <h1 class="m-0">Create Package</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito niyo lagay kung nasaang page kayo. -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="homis/dashboard">Home</a></li>
              <li class="breadcrumb-item active">Create Package</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content" >
          <form action="create-package.php" method="POST" name="add_name" id="add_name">
            <div class="row">
              <div class="col-sm-6">
                <div class="container">
                  <div class="form-group">
                    <label for="id">Package #:</label>
                <!--<input type="hidden" class="form-control" id="id" value="<?php echo $row['id']+1; ?>" name="id" >
                    <input type="text" class="form-control" id="id"  value="<?php echo $row['id']+1; ?>" name="id" disabled>
                --></div>
                    <div class="form-group">
                    <label for="name">Package Name:</label>
                    <input type="text" class="form-control" id="name1" placeholder="Enter Package Name" name="name1">
                    </div>
                    <div class="form-group">
                    <label for="price">Package Price:</label>
                    <input type="number" class="form-control" id="price" placeholder="Enter Package Price" name="price">
                    </div>
                    <div class="form-group">
                    <label for="desc">Package Description:</label>
                    <textarea type="text" class="form-control" id="desc" placeholder="Enter Package Description" name="desc"></textarea>
                    </div>
                </div>
              </div>
                <div class="col-sm-6">
                  <div class="container">
                    <div class="form-group">
                        <span>Inclusion(s):</span>
                        <table id="dynamic_field"> 
                        <br> 
                        <tr style="height:45px;">  
                          <td><input type="text" name="name[]" placeholder="Enter Additional" class="form-control name_list" /></td>  
                          <td><button type="button" name="add" id="add" class="btn btn-success">Add More</button></td>  
                        </tr>
                        </table>  
                      </div>
                  </div>
              </div> 
            <div class="col-sm-6">
              <div class="container"> 
                <button type="submit" name="submit" class="btn btn-primary">Submit</button>
              </div>
            </div> 
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<?php 
  include VIEW . 'footer.phtml'; 
?>

<script>  
$(document).ready(function(){  
     var i=1;  
     $('#add').click(function(){  
          i++;  
          $('#dynamic_field').append('<tr id="row'+i+'"><td><input type="text" name="name[]" placeholder="Enter your Name" class="form-control name_list" /></td><td><button type="button" name="remove" id="'+i+'" class="btn btn-danger btn_remove">X</button></td></tr>');  
     });  
     $(document).on('click', '.btn_remove', function(){  
          var button_id = $(this).attr("id");   
          $('#row'+button_id+'').remove();  
     });  
     $('#submit').click(function(){            
          $.ajax({  
               url:"create_package.php",  
               method:"POST",  
               data:$('#add_name').serialize(),  
               success:function(data)  
               {  
                    alert(data);  
                    $('#add_name')[0].reset();  
               }  
          });  
     });  
});  
</script>