
<?php 
  include VIEW . 'header.phtml'; 
?>
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">

            <!--- Title to ng page na pinasok niyo -->
            <h1 class="m-0">Avail Package List</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito niyo lagay kung nasaang page kayo. -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="homis/dashboard">Home</a></li>
              <li class="breadcrumb-item active">Avail Package List</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content" >
    <a class="btn btn-primary text-white"  style="float:right;" data-toggle="modal" data-target="#exampleModal">Add Patient Avail</a>
    <?php
        if(isset($this->view_data['message'])){
            ?>
              <div class="alert alert-<?=$this->view_data['alert']?>">
                <?=$this->view_data['message']?>
              </div>
            <?php
        }
      ?>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
          <tr>
            <th>#</th>
            <th class="th-sm">Patient Name
            </th>
            <th class="th-sm">Package Name
            </th>
            <th class="th-sm">Department
            </th>
            <th class="th-sm">Avail Date
            </th>
            <th class="th-sm">Examination Date
            </th>
            <th class="th-sm">Action
            </th>
          </tr>
        </thead>
        <tbody>
            <?php
                $count = 1;
                foreach ($this->view_data['availData'] as $row) {
            ?>
          <tr>
            <td><?php echo $count++ ?></td>
            <td><?php echo $row['patient_name'] ?></td>
            <td><?php echo $row['mp_name'] ?></td>
            <td><?php echo $row['department'] ?></td>
            <td><?php echo date_format(date_create($row['created_at']),"F d, Y H:s a") ?></td>
            <td><?php echo date_format(date_create($row['exam_date']),"F d, Y") ?></td>
            <td><center><a href="/medPackage/medPackageAvailView/<?php echo $row['id']; ?>" class="btn btn-info btn-sm">View</a></center></td>
          </tr>
           <?php
                $count++;
                }
            ?>
        </tbody>
      </table>
    </section>
    <!-- /.content -->
  </div>
<!-- Modal -->
<form method="POST" action="addPatientAvail">
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Adding Patient Avail</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
          <div class="form-group">
          <label for="name">Patient Name:</label>
          <input type="text" name="patientName" class="form-control" id="name" placeholder="Enter Patient Name">
        </div>
        <div class="form-group">
         <label for="package">Select Medical Package:</label>
          <select name="medPackId" class="form-control">
            <option selected disabled>--SELECT PACKAGE--</option>
              <?php
                foreach ($this->view_data['viewPackage'] as $addPatientAvail) {
                  echo "<option value='".$addPatientAvail['id']."' >".$addPatientAvail['mp_name']."</option>";
                }
              ?>
            </select>
          </div>
            <div class="form-group">
              <label for="name">Department:</label>
              <select name="department" class="form-control">
                <option selected disabled>--SELECT DEPARTMENT--</option>
                <option value="Inpatient" >Inpatient</option>
                <option value="Outpatient" >Outpatient</option>
              </select>
            </div>
          </select>
          <div class="form-group">
            <label for="exam_date">Examination date:</label>
            <input type="datetime-local" name="exam_date" date-format="YYYY-mm-dd HH:MI:SS" class="form-control" id="exam_date">
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-primary" name="save" value="Save">
      </div>
    </div>
  </div>
</div>
</form>
<?php
  include VIEW . 'footer.phtml'; 
?>