<?php include VIEW . 'header.phtml'; ?>

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">

            <!--- Title to ng page na pinasok niyo -->
            <h1 class="m-0">Medical Package</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito niyo lagay kung nasaang page kayo. -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="homis/dashboard">Home</a></li>
              <li class="breadcrumb-item active">Medical Package</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content" >

          <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
              <tr>
                <th>#</th>
                <th class="th-sm">Package Name
                </th>
                <th class="th-sm">Price
                </th>
                <th class="th-sm">Description
                </th>
                <th class="th-sm">Action
                </th>
              </tr>
            </thead>
          <tbody>
            <?php
                $count = 1;
                foreach ($this->view_data['mainData'] as $row) {
            ?>
            <tr>
              <td><?php echo $count++ ?></td>
              <td><?php echo $row['mp_name'] ?></td>
              <td><?php echo $row['mp_price'] ?></td>
              <td><?php echo $row['mp_desc'] ?></td>
              <td align="center"><a href="/medPackage/medPackageView/<?php echo $row['id']; ?>" title="View">View</a></td>
            </tr>
            <?php
                $count++;
                }
              ?>
          </tbody>
        </table>


        </div>
       

    </section>
    <!-- /.content -->
  </div>

<script>
  $(document).ready( function () {
    $('#myTable').DataTable();
} )
</script>

<?php include VIEW . 'footer.phtml'; ?>