<?php include VIEW . 'header.phtml'; ?>

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">

            <!--- Title to ng page na pinasok niyo -->
            <h1 class="m-0">Package Information</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito niyo lagay kung nasaang page kayo. -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="homis/dashboard">Home</a></li>
              <li class="breadcrumb-item active">Package Information</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
        <a  href="/medPackage/medPackageList/" button class="btn btn-primary text-white"  style="float:right; ">BACK</a>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
          <div class="card-body">
            <div class="row">
              <div class="col-sm-6">
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <p class="mb-0 text-gray"><b>Package Name: </b> <br><?php echo ucfirst($this->view_data['medPackageInfo'][0]['mp_name']); ?></p><br>
              </div>
              <p class="mb-0 text-gray"><b>Package Price: </b> <br><?php echo ucfirst($this->view_data['medPackageInfo'][0]['mp_price']); ?></p><br>
              <p class="mb-0 text-gray"><b>Package Descption: </b> <br><?php echo ucfirst($this->view_data['medPackageInfo'][0]['mp_desc']); ?></p><br>
              <br><br>
              
           </div>
            <div class="col-sm-6">
            <h5 class="mb-4 text-gray-800"><b>Inclusion(s)</b></h5>
              <?php
                  $count = 1;
                  foreach ($this->view_data['medPackageInfo'] as $row) {
              ?>
                <p class="mb-1 text-gray">- <?php echo $row['testname'] ?></p>
              <?php
                  }
              ?>  
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

<?php
    include VIEW . 'footer.phtml';
?>