<?php include VIEW . 'header.phtml'; ?>

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">

            <!--- Title to ng page na pinasok niyo -->
            <h1 class="m-0">Avail Package List</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito niyo lagay kung nasaang page kayo. -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="homis/dashboard">Home</a></li>
              <li class="breadcrumb-item active">Avail Package List</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content" >

          <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
          <tr>
            <th>#</th>
            <th class="th-sm">Patient Name
            </th>
            <th class="th-sm">Package Name
            </th>
            <th class="th-sm">Department
            </th>
            <th class="th-sm">Avail Date
            </th>
            <th class="th-sm">Examination Date
            </th>
            <th class="th-sm">Action
            </th>
          </tr>
        </thead>
        <tbody>
            <?php
                $count = 1;
                foreach ($this->view_data['availData'] as $row) {
            ?>
          <tr>
            <td><?php echo $count++ ?></td>
            <td><?php echo $row['patient_name'] ?></td>
            <td><?php echo $row['mp_name'] ?></td>
            <td><?php echo $row['department'] ?></td>
            <td><?php echo date_format(date_create($row['created_at']),"F d, Y H:s a") ?></td>
            <td><?php echo date_format(date_create($row['exam_date']),"F d, Y") ?></td>
            <td><center><a href="avail-view.php?id=<?php echo $row['0'] ?>" class="btn btn-info btn-sm">View</a></center></td>
          </tr>
           <?php
                $count++;
                }
            ?>
        </tbody>
      </table>
  </div>
</div>
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
 <form action="avail.php" method="POST">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Adding Patient Avail</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div class="form-group">
      <label for="name">Patient Name:</label>
      <input type="text" name="name" class="form-control" id="name" placeholder="Enter Patient Name">
    </div>
    <div class="form-group">
      <label for="package">Medical Package:</label>
      <select name="package" class="form-control">
        <option selected disabled>--SELECT PACKAGE--</option>
        <?php
            foreach ($this->view_data['availData'] as $row) {
                echo "<option value='".$row['id']."'>".$row['mp_name']."</option>";
            }
        ?>
        </select>
      </div>
        <div class="form-group">
          <label for="name">Department:</label>
          <select name="department" class="form-control">
            <option selected disabled>--SELECT DEPARTMENT--</option>
            <option value="Inpatient" >Inpatient</option>
            <option value="Outpatient" >Outpatient</option>
          </select>
        </div>
       </select>
       <div class="form-group">
        <label for="exam_date">Examination date:</label>
        <input type="datetime-local" name="exam_date" date-format="YYYY-mm-dd HH:MI:SS" class="form-control" id="exam_date">
       </div>
      
    </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success" name="submit">Submit</button>
      </div>
    </div>
  </form>
  </div>
</div>

<?php 
  include VIEW . 'footer.phtml'; 
?>
