<?php 
  include VIEW . 'header.phtml'; 
?>

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">

            <!--- Title to ng page na pinasok niyo -->
            <h1 class="m-0">Avail Package List</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito niyo lagay kung nasaang page kayo. -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="homis/dashboard">Home</a></li>
              <li class="breadcrumb-item active">Avail Package List</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content" >

    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
          <tr>
            <th>#</th>
            <th class="th-sm">ID
            </th>
            <th class="th-sm">Patient Name
            </th>
            <th class="th-sm">Package Name
            </th>
            <th class="th-sm">Department
            </th>
            <th class="th-sm">Avail Date
            </th>
            <th class="th-sm">Examination Date
            </th>
            <th class="th-sm">Action
            </th>
          </tr>
        </thead>
        <tbody>
            <?php
                $count = 1;
                foreach ($this->view_data['availData'] as $row) {
            ?>
          <tr>
            <td><?php echo $count++ ?></td>
            <td><?php echo $row['id'] ?></td>
            <td><?php echo $row['patient_name'] ?></td>
            <td><?php echo $row['mp_name'] ?></td>
            <td><?php echo $row['department'] ?></td>
            <td><?php echo date_format(date_create($row['created_at']),"F d, Y H:s a") ?></td>
            <td><?php echo date_format(date_create($row['exam_date']),"F d, Y") ?></td>
            <td><center><a href="/medPackage/medPackageAvailView/<?php echo $row['id']; ?>" class="btn btn-info btn-sm">View</a></center></td>
          </tr>
           <?php
                $count++;
                }
            ?>
        </tbody>
      </table>
       
    </section>
    <!-- /.content -->
  </div>

<?php
  include VIEW . 'footer.phtml'; 
?>