<?php include VIEW . 'header.phtml'; ?>
<?php include VIEW . 'navigation.phtml'; ?>

<!--<?php
  //foreach ($this->view_data['dataRecords1'] as $data) {
    //echo $data['drug_id']."<br>";
  //}
  //$drug12 //= $this->view_data['dataRecords2'];
  //echo $drug12[0]['drug_name'];
?>
-->


<div class="row">
	<!-- DRUG NAMES -->
	<div class="col-sm">
		<div class="card rounded w-33.33 ml-3">
			<p class="h2 d-flex justify-content-center"><b>Names</b></p>
			<p class=" justify ml-5">
				<?php
  					foreach ($this->view_data['dataRecords1'] as $data) {
    					echo $data['drug_name']."<br>";
  					}
				?>
			</p>
		</div>
	</div>
	<!-- DRUG TYPES -->
	<div class="col-sm">
		<div class="card rounded w-33.33">
			<p class="h2 d-flex justify-content-center"><b>Types</b></p>
			<p class=" justify ml-5">
				<?php
					foreach ($this->view_data['dataRecords1'] as $data){
						echo $data['drug_type']. "<br>";
					}
				?>
			</p>
		</div>
	</div>
	<!-- DRUG PRICES -->
	<div class="col-sm">
		<div class="card rounded w-33.33 mr-3">
			<p class="h2 d-flex justify-content-center"><b>Prices</b></p>
			<p class=" justify ml-5">
				<?php
					foreach ($this->view_data['dataRecords1'] as $data ) {
						echo $data['drug_price']. "<br>";
					}
				?>
			</p>
		</div>
	</div>
	<!-- DRUG DESCRIPTIONS -->
	<!-- <div class="col-sm">
		<div class="card rounded w-33.33 mr-3">
			<p class="h2 d-flex justify-content-center"><b>Descriptions</b></p>
			<p class=" justify ml-5">
				<?php
					//foreach ($this->view_data['dataRecords1'] as $data ) {
					//	echo $data['drug_description']. "<br>";
					//}
				?>
			</p>
		</div>
	</div> -->
</div>



<?php include VIEW . 'footer.phtml'; ?>