<?php include VIEW . 'header.phtml'; ?>

<!--<?php
  //foreach ($this->view_data['dataRecords1'] as $data) {
    //echo $data['drug_id']."<br>";
  //}
  //$drug12 //= $this->view_data['dataRecords2'];
  //echo $drug12[0]['drug_name'];
?>
-->



<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">

            <!--- Title to ng page na pinasok niyo -->
            <h1 class="m-0">Homis Dashboard</h1>

          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito niyo lagay kung nasaang page kayo. -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Drug List </li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content" >
<!-- Data of cards -->
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
              <div class="card-body">
                <h5 class="card-title d-flex justify-content-center">NO. OF DRUGS</h5>
                <p class="card-text h3 d-flex justify-content-center">
                  <?php
                    $totalDrugs = $this->view_data['dataRecords2'];
                      echo $totalDrugs[0][0];
                  ?>
                </p>
              </div>
        </div>
      </div>
      <div class="col-sm">
        <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
              <div class="card-body">
                <h5 class="card-title d-flex justify-content-center">NO. OF STOCKS</h5>
                <p class="card-text h3 d-flex justify-content-center">
                  <?php
                    $totalStocksDrugs = $this->view_data['dataRecords3'];
                      echo $totalStocksDrugs[0][0];
                  ?>
                </p>
              </div>
        </div>
      </div>
      <div class="col-sm">
        <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
              <div class="card-body">
                <h5 class="card-title d-flex justify-content-center">TRANSACTIONS</h5>
                <p class="card-text h3 d-flex justify-content-center">
                  <?php
                    $totaTransactions = $this->view_data['dataRecords4'];
                      echo $totaTransactions[0][0];
                  ?>
                </p>
              </div>
        </div>
      </div>
      <div class="col-sm">
        <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
              <div class="card-body">
                <h5 class="card-title d-flex justify-content-center">NO. OF PAYMENTS</h5>
                <p class="card-text h3 d-flex justify-content-center">
                  <?php
                    $totalPayments = $this->view_data['dataRecords5'];
                      echo $totalPayments[0][0];
                  ?>
                </p>
              </div>
        </div>
      </div>
    </div>
  </div>
  <!-- chart -->
  <canvas id="homisChart"></canvas>

  </div>
       

  </section>
    <!-- /.content -->
  </div>
	

<?php include VIEW . 'footer.phtml'; ?>




