<?php 
  include VIEW . 'header.phtml'; 
?>

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">

            <!--- Title to ng page na pinasok niyo -->
            <h1 class="m-0">Diet Plan List</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito niyo lagay kung nasaang page kayo. -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="homis/dashboard">Home</a></li>
              <li class="breadcrumb-item active">Diet Plan List</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
      <button style="float:right;" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalx">Set Patient Diet Plan</button>
    </div>
    <!-- /.content-header -->

    <!-- Main content --><br><br>
    <section class="content" >
          <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
              <tr>
                <th>#</th>
                <th class="th-sm">Disease Name
                </th>
                <th class="th-sm">Description
                </th>
                <th class="th-sm">Action
                </th>
              </tr>
            </thead>
          <tbody>
            <?php
                $count = 1;
                foreach ($this->view_data['dietPlanData'] as $row) {
            ?>
            <tr>
              <td><?php echo $count++ ?></td>
              <td><?php echo $row['Disease'] ?></td>
              <td><?php echo substr($row['dp_desc'],0,50) ?></td>
              <td align="center"><a href="/dietManagement/dietPlanView/<?php echo $row['id']; ?>" class="btn btn-info btn-sm">View</a></td>
            </tr>
            <?php
                $count++;
                }
              ?>
          </tbody>
        </table>


        </div>
       

    </section>
    <!-- /.content -->
  </div>
<form action="setDietPlan" method="POST">
  <div class="modal fade" id="exampleModalx" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Set Patient Diet Plan</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          <div class="form-group">
            <label for="Patient Name">Patient Name:</label>
            <input type="text" name="patientName" class="form-control" id="patientName">
          </div>

          <div class="form-group">
            <label for="Disease">Disease:</label>
            <select name="selected" class="form-control">
            <option selected disabled>--SELECT PACKAGE--</option>
            <?php
                foreach ($this->view_data['dietPlanData'] as $row){
                    echo "<option value='".$row['id']."' >".$row['Disease']."</option>";
                }
            ?>
            
            </select>
          </div>
          <div class="form-group">
            <label for="expirationDate">Until Date</label>
            <input type="date" name="untilDate" class="form-control" id="untilDate">
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <input type="submit" class="btn btn-primary" name="setSubmit" value="Submit">
        </div>
      </div>
    </div>
  </div>
</form>

<script>
  $(document).ready( function () {
    $('#myTable').DataTable();
} )
</script>

<?php include VIEW . 'footer.phtml'; ?>