<?php include VIEW . 'header.phtml'; ?>

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">

            <!--- Title to ng page na pinasok niyo -->
            <h1 class="m-0">Diet Plan Information</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito niyo lagay kung nasaang page kayo. -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="homis/dashboard">Home</a></li>
              <li class="breadcrumb-item active">Diet Plan Information</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
        <a  href="/dietManagement/dietPlanList" button class="btn btn-primary text-white"  style="float:right; margin-left:5px">BACK</a>
        <a href="/dietManagement/dietReport/<?php echo $this->view_data['dietPlanView'][0]['id']; ?>" target="_blank" class="btn btn-danger" style="float:right;">View Report</a>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
          <div class="card-body">
            <div class="row">
              <div class="col-sm-12">
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
              </div>
                <h5><b>Patient Name: </b> <br><?php echo ucfirst($this->view_data['dietPlanView'][0]['patient_fullname']); ?></h5><br>
                <h5><b>Nutritionist Name: </b> <br><?php echo ucfirst($this->view_data['dietPlanView'][0]['firstname']." ".$this->view_data['dietPlanView'][0]['middlename']." ".$this->view_data['dietPlanView'][0]['lastname']); ?></h5><br>
                <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h4>Monday</h4>
                  <p><b>Break Fast: </b> <br><?php echo ucfirst($this->view_data['monday'][0]['breakfast']); ?></p><br>
                  <p><b>Lunch: </b> <br><?php echo ucfirst($this->view_data['monday'][0]['lunch']); ?></p><br>
                  <p><b>Dinner: </b> <br><?php echo ucfirst($this->view_data['monday'][0]['dinner']); ?></p><br>
                  <!--<input value="edit" href="#" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">-->
                </div>
                <div class="col-sm-3">
                  <h4>Tuesday</h4>
                  <p><b>Break Fast: </b> <br><?php echo ucfirst($this->view_data['tuesday'][0]['breakfast']); ?></p><br>
                  <p><b>Lunch: </b> <br><?php echo ucfirst($this->view_data['tuesday'][0]['lunch']); ?></p><br>
                  <p><b>Dinner: </b> <br><?php echo ucfirst($this->view_data['tuesday'][0]['dinner']); ?></p><br>
                  <!--<input value="edit" href="#" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">-->
                </div>
                <div class="col-sm-3">
                  <h4>wednesday</h4>
                  <p><b>Break Fast: </b> <br><?php echo ucfirst($this->view_data['wednesday'][0]['breakfast']); ?></p><br>
                  <p><b>Lunch: </b> <br><?php echo ucfirst($this->view_data['wednesday'][0]['lunch']); ?></p><br>
                  <p><b>Dinner: </b> <br><?php echo ucfirst($this->view_data['wednesday'][0]['dinner']); ?></p><br>
                  <!--<input value="edit" href="#" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">-->
                </div>
                <div class="col-sm-3">
                  <h4>Thursday</h4>
                  <p><b>Break Fast: </b> <br><?php echo ucfirst($this->view_data['thursday'][0]['breakfast']); ?></p><br>
                  <p><b>Lunch: </b> <br><?php echo ucfirst($this->view_data['thursday'][0]['lunch']); ?></p><br>
                  <p><b>Dinner: </b> <br><?php echo ucfirst($this->view_data['thursday'][0]['dinner']); ?></p><br>
                  <!--<input value="edit" href="#" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">-->
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h4>Friday</h4>
                  <p><b>Break Fast: </b> <br><?php echo ucfirst($this->view_data['friday'][0]['breakfast']); ?></p><br>
                  <p><b>Lunch: </b> <br><?php echo ucfirst($this->view_data['friday'][0]['lunch']); ?></p><br>
                  <p><b>Dinner: </b> <br><?php echo ucfirst($this->view_data['friday'][0]['dinner']); ?></p><br>
                  <!--<input value="edit" href="#" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">-->
                </div>
                <div class="col-sm-3">
                  <h4>Saturday</h4>
                  <p><b>Break Fast: </b> <br><?php echo ucfirst($this->view_data['saturday'][0]['breakfast']); ?></p><br>
                  <p><b>Lunch: </b> <br><?php echo ucfirst($this->view_data['saturday'][0]['lunch']); ?></p><br>
                  <p><b>Dinner: </b> <br><?php echo ucfirst($this->view_data['saturday'][0]['dinner']); ?></p><br>
                  <!--<input value="edit" href="#" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">-->
                </div>
                <div class="col-sm-3">
                  <h4>Sunday</h4>
                  <p><b>Break Fast: </b> <br><?php echo ucfirst($this->view_data['sunday'][0]['breakfast']); ?></p><br>
                  <p><b>Lunch: </b> <br><?php echo ucfirst($this->view_data['sunday'][0]['lunch']); ?></p><br>
                  <p><b>Dinner: </b> <br><?php echo ucfirst($this->view_data['sunday'][0]['dinner']); ?></p><br>
                  <!--<input value="edit" href="#" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">-->
                </div>
              </div>
           </div>
          </div>
        </div>
    </div>
  </div>
</div>

<!-- Modal -->
<form action="/dietManagement/addStock/<?php echo $this->view_data['monday'][0]['diet_id']; ?>" method="POST">
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
  </form>
<?php
    include VIEW . 'footer.phtml';
?>