<!-- HMS Header-->
<?php include VIEW . 'header.phtml'; ?>


<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <!--- I chchange natin ito Base sa name ng Function -->
            <h1 class="m-0">Pharmacy Transaction</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito naman natin ilalagay kung nasaan part na tayo ng site up to 2 only -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/homis/dashboard">Home</a></li>
              <li class="breadcrumb-item active">Transaction View </li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content" >

      <table id="example" class="table table-striped table-bordered" style="width:100%">
          <thead align="center">
            <th>#</th>
            <th>Transaction No</th>
            <th>Date</th>
            <th>Action</th>
          </thead>
          <tbody>
            <?php
            $count = 1;
              foreach ($this->view_data['trans'] as $data) {
                ?>
            <tr>
              <td align="center">
                <?php echo $count; ?>
              </td>
              <td align="center">
                <?php echo $data["transactionNo"]; ?>
              </td>
              <td align="center">
                <?php
                          $convert = new DateTime($data["created_at"]); //create datetime object with received data
                          $date = $convert->format('M d, Y'); 
                          $time = $convert->format('h:m A');
                          echo "<strong>Date:</strong> ".$date." <strong>Time:</strong> ".$time;
                      ?>
              </td>
              <td align="center">
                <a href="/pharmacy/transactionView/<?php echo $data['transactionNo'] ?>" class="btn btn-primary btn-sm">View</a>
              </td>
            </tr>
                <?php
                $count++;
              }
            ?>
          </tbody>
        </table>

    </section>
    <!-- /.content -->
  </div>


<?php include VIEW . 'footer.phtml'; ?>
