<!-- HMS Header-->
<?php 
  include VIEW . 'header.phtml'; 
  $total = null;
?>


<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <!--- I chchange natin ito Base sa name ng Function -->
            <h1 class="m-0">Pharmacy Transaction</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito naman natin ilalagay kung nasaan part na tayo ng site up to 2 only -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/homis/dashboard">Home</a></li>
              <li class="breadcrumb-item active">Transaction View </li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content" > 


          <div class="row">
            <div class="col">
              <h4>Transaction Number: <strong><?php echo $this->view_data['trans'][0]['transactionNo']; ?></strong></h4>
            </div>
            <div class="col">
              <?php
                      $convert = new DateTime($this->view_data['trans'][0]["created_at"]); //create datetime object with received data
                      $date = $convert->format('M d, Y'); 
                      $time = $convert->format('h:m A');
                      echo "<small style='float:right;'><strong>Date:</strong> ".$date." <strong>Time:</strong> ".$time."</small>";
                  ?>
            </div>
          </div>
          <hr>
          <h5>Orders:</h5>

          <div class="row">
            <div class="col">
              <strong>NAME</strong>
            </div>
            <div class="col">
              <strong>PRICE</strong>
            </div>
            <div class="col">
              <strong>QUANTITY</strong>
            </div>
            <div class="col">
              <strong>AMOUNT</strong>
            </div>
          </div>
          <br>
          <?php
            foreach ($this->view_data['trans'] as $rows) {
                    $price = $rows['amount'];
                    $total+=$price * $rows['quantity'];
        ?>
        <br>
        <div class="row">
            <div class="col">
              <?php echo $rows['drug_name']; ?>
            </div>
            <div class="col">
              PHP <?php echo number_format($price,2); ?>
            </div>
            <div class="col">
              <?php echo $rows['quantity']; ?>
            </div>
            <div class="col">
              PHP <?php echo number_format($price * $rows['quantity'],2); ?>
            </div>
          </div>
        <?php
            }
          ?>
                <hr>
                <div class="row">
                    <div class="col">

                    </div>
                    <div class="col">

                    </div>
                </div>
                <div class="row">
                    <div class="col">

                    </div>
                    <div class="col">

                    </div>
                    <div class="col">
                        Sub Total:
                    </div>
                    <div class="col">
                        PHP <strong><?php  echo number_format($total,2); ?></strong>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col">

                    </div>
                    <div class="col">

                    </div>
                    <div class="col-6">
                        <a href="/pharmacy/receipt/<?php echo $this->view_data['trans'][0]['transactionNo']; ?>" target="_blank" class="btn btn-primary btn-sm btn-block">View Receipt</a>
                    </div>
                </div>


    </section>
    <!-- /.content -->
  </div>


<?php include VIEW . 'footer.phtml'; ?>
