<!-- HMS Header-->
<?php include VIEW . 'header.phtml'; ?>


<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">

            <!--- Title to ng page na pinasok niyo -->
            <h1 class="m-0">MEDICAL RECORDS</h1>

          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito niyo lagay kung nasaang page kayo. -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Medical Records </li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
      <a href="/medicalRecords/medRecords" button class="btn btn-primary text-white"  style="float:right; margin-left:5px">BACK</a>
    </div><br><br>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content" >
        <div class="row">
        
          <div class="col-sm-6">
          <h4>Patient Information</h4><br>
            <p>Patient Name: <strong><?php echo $this->view_data['medView'][0]['patient_fullname'] ?></strong></p>
            <p>Address: <strong><?php echo $this->view_data['medView'][0]['patient_fulladdress']; ?></strong></p>
            <p>Birthdate: 
              <strong>
                <?php
                  foreach ($this->view_data['medicalRecords'] as $row) {
                  $convert = new DateTime($row['patient_birthdate']); //create datetime object with received data
                              $date = $convert->format('M d, Y');
                              echo "<strong>$date</strong> ";
                  }
                ?>
              </strong>
            </p>
            <p>Citizenship:
              <strong>
                <?php echo $row['patient_citizenship']; ?>
              </strong>
            </p>
            <p>Gender:
              <strong>
                <?php echo $row['patient_gender']?>
              </strong>
            </p>
            <p>Civil Status:
              <strong>
                <?php echo $row['patient_civilstatus']; ?>
              </strong>
            </p>       
            <p><medium>Contact No:<strong>&nbsp;<?php echo $this->view_data['medView'][0]['patient_mobileno']; ?></strong></medium></p>
            <br><h4>Emergency Contact</h4><br>     
                    <?php 
                    echo "<p><strong>&emsp;".$row['patient_contact1']."<br>&emsp;".
                      $row['patient_contact2']."</strong></p>";
                  ?>
          </div>
          <div class="col-sm-6">
            <p>Schedule:
                <strong>
                  <?php
                  foreach ($this->view_data['medicalRecords'] as $row) {  
                    $convert = new DateTime($row['apt_sched_date']); //create datetime object with received data
                      $date = $convert->format('M d, Y');
                        echo "<strong>$date</strong> | "; 
                    $convert1 = new DateTime($row['apt_sched_time']);
                      $time = $convert->format('h:i:s A');
                        echo "<strong>$time</strong>";
                      }
                  ?>
                </strong>
              </p>
              <p>Hospital:
                <strong>
                  <?php 
                    echo $row['patient_prev_hospital'];
                  ?>
                </strong>
             </p>
             <p>Visit:
                <?php 
                foreach ($this->view_data['medicalRecords'] as $row) {
                  $convert = new DateTime($row['apt_patient_lastvisit']); //create datetime object with received data
                            $date = $convert->format('M d, Y');
                            echo "<strong>$date</strong> ";
                }
                ?>
              </p>
              <p>Health Insurance:
                <strong>
                  <?php 
                    echo $row['patient_health_insurance'];
                  ?>
                </strong>
              </p>
              <p>Philhealth:
                <strong>
                  <?php 
                    echo $row['patient_philhealth'];
                  ?>
                </strong>
              </p>
              <p>Doctor:
                <strong>
                  <?php 
                    echo $row['apt_doctors_name'];
                  ?>
                </strong>
              </p>
              <p>Patient Disorder:
                <strong>
                  <?php 
                    echo $row['patient_disorder'];
                  ?>
                </strong>
              </p>
              <p>Cause:
                <strong>
                  <?php echo $row['apt_sched_cause'];?>
                </strong>
              </p>
              <p>Remarks:
                <strong>
                  <?php echo $row['apt_remarks'];?>
                </strong>
              </p>
          </div>
        </div>
    </section>
    <!-- /.content -->
  </div>


<?php include VIEW . 'footer.phtml'; ?>
