<?php
	foreach ($this->view_data['patientRecordPdf'] as $row) {
	
if(isset($row['apt_id'])){


		
		require('fpdf17/fpdf.php');

		//A4 width : 219mm
		//default margin : 10mm each side
		//writable horizontal : 219 (10*2) = 189mm

		$pdf = new FPDF('P','mm',array(210,297));

		$pdf->AddPage();

		//set font to arial, bold, 14pt
		$pdf->SetFont('Times','B','16');

		//Cell( width, height, text, border, end line, [align] )
		$pdf->cell(0,10,'',0,1,0);
		$pdf->Cell(0,0, 'Medlink Pharmacy',0,1,'C');
		$pdf->SetFont('Times','B','12');
		$pdf->Cell(0,10, '#541 greenhills exit. Quezon city', 0,1,'C');
		$pdf->Cell(0,5,'',0,1,0);
		$pdf->SetFont('Arial','B','14');
		$pdf->cell(0,0,'',1,1,0);
		$pdf->Cell(0,20,$row['patient_fullname'],0,1,2);
		$pdf->Cell(0  ,4,'',0,1);

		$pdf->Cell(0  ,4,'',0,1);


		$pdf->Cell(0  ,2.5,'TOTAL :',0,0,'C');
		$pdf->Cell(5  ,2.5,"PHP ",0,1,'R');

		$pdf->Cell(0  ,4,'',0,1);

		$pdf->Cell(0  ,4,'THANK YOU FOR TRUSTING US!',0,1,'C');
		$pdf->Cell(0  ,2,'PLEASE COME AGAIN!',0,1,'C');


		$pdf->Output();
	}
}

?>