<!-- HMS Header-->
<?php include VIEW . 'header.phtml'; ?>


<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="content">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">

            <!--- Title to ng page na pinasok niyo -->
            <h1 class="m-0">MEDICAL RECORDS</h1>

          </div><!-- /.col -->
          <div class="col-sm-6">
            <!-- Dito niyo lagay kung nasaang page kayo. -->
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Medical Records </li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content" >
        
        <div class="container">
            <?php
             foreach ($this->view_data['patientRecord'] as $row) {
            ?>
          <div class="row">
            <div class="col"></div>
            <div class="col">
              <h4>Schedule:
                <strong>
                  <?php
                    $convert = new DateTime($row['apt_sched_date']); //create datetime object with received data
                      $date = $convert->format('M d, Y');
                        echo "<strong>$date</strong> | "; 
                    $convert1 = new DateTime($row['apt_sched_time']);
                      $time = $convert->format('h:i:s A');
                        echo "<strong>$time</strong>";
                  ?>
                </strong>
              </h4>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <h4>Patient Name: <strong><?php echo $row['patient_fullname']; ?></strong></h4>
            </div>
            <div class="col">
              <?php
                $status = $row['patient_status'];
                $color = "";
                if($status=="Registered"){
                  $color = "green";
                }else{
                  $color = "#ff9966";
                }
              ?>
              <h5>Status:
                <span style="color:<?php echo $color; ?>"><strong><?php echo $status; ?></strong></span>
              </h5>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <h5>Address:
                <strong>
                <?php
                  echo ucfirst($row['patient_fulladdress']."&nbsp;|&nbsp;".$row['patient_mobileno']);
                ?>
                </strong>
              </h5>
            </div>
            <div class="col">
              <h5>Occupation:
                <strong>
                  <?php echo $row['patient_occupation'];?>
                </strong>
              </h5>
            </div>
          </div>
          <h5>Birthdate: 
            <strong>
              <?php
                $convert = new DateTime($row['patient_birthdate']); //create datetime object with received data
                            $date = $convert->format('M d, Y');
                            echo "<strong>$date</strong> ";
              ?>
            </strong>
          </h5>
          <h5>Citizenship:
            <strong>
              <?php echo $row['patient_citizenship']; ?>
            </strong>
          </h5>
          <h5>Gender:
            <strong>
              <?php echo $row['patient_gender']?>
            </strong>
          </h5>
          <h5>Civil Status:
            <strong>
              <?php echo $row['patient_civilstatus']; ?>
            </strong>
          </h5>
          <div style ="height:10px;" class="bg-dark"></div>
          <h4>Hospital:
            <strong>
              <?php 
                echo $row['patient_prev_hospital'];
              ?>
            </strong>
          </h4>
          <div class="row">
            <div class="col">
              <h4>Visit:
                <?php 
                  $convert = new DateTime($row['apt_patient_lastvisit']); //create datetime object with received data
                            $date = $convert->format('M d, Y');
                            echo "<strong>$date</strong> ";
                ?>
              </h4>
            </div>
            <div class="col">
            </div>
          </div>
          <div class="row">
            <div class="col">
              <h4>Health Insurance:
                <strong>
                  <?php 
                    echo $row['patient_health_insurance'];
                  ?>
                </strong>
              </h4>
            </div>
            <div class="col">
              <h4>Philhealth:
                <strong>
                  <?php 
                    echo $row['patient_philhealth'];
                  ?>
                </strong>
              </h4>
            </div>
          </div>
          <div style ="height:10px;" class="bg-dark"></div>
            <h4>Doctor:
              <strong>
                <?php 
                  echo $row['apt_doctors_name'];
                ?>
              </strong>
            </h4>
            <h4>Patient Disorder:
              <strong>
                <?php 
                  echo $row['patient_disorder'];
                ?>
              </strong>
            </h4>
            <h4>Cause:
              <strong>
                <?php echo $row['apt_sched_cause'];?>
              </strong>
            </h4>
            <h4>Remarks:
              <strong>
                <?php echo $row['apt_remarks'];?>
              </strong>
            </h4>
            
            <div style="height:auto;" class="text-light bg-dark"><h4>&nbsp;Emergency Contact</h4></div>
            <?php 
              echo "<h4><strong>&emsp;".$row['patient_contact1']."<br>&emsp;".
                $row['patient_contact2']."</strong></h4>";
            ?>
          <?php 
            }
          ?>
        </div>
      
        
        
        
  </div>

       

    </section>
    <!-- /.content -->
  </div>


<?php include VIEW . 'footer.phtml'; ?>
