<?php
	foreach ($this->view_data['patientRecordPdf'] as $row) {
	
if(isset($row['apt_id'])){


		
		require('fpdf17/fpdf.php');

		//A4 width : 219mm
		//default margin : 10mm each side
		//writable horizontal : 219 (10*2) = 189mm

		$pdf = new FPDF('P','mm',array(210,297));

		$pdf->AddPage();

		//set font to arial, bold, 14pt
		$pdf->SetFont('Times','B','16');

		//Cell( width, height, text, border, end line, [align] )
		$pdf->cell(0,10,'',0,1,0);
		$pdf->Cell(0,0, 'Medlink Pharmacy',0,1,'C');
		$pdf->SetFont('Times','B','12');
		$pdf->Cell(0,10, '#541 greenhills exit. Quezon city', 0,1,'C');
		$pdf->Cell(0,5,'',0,1,0);
		$pdf->SetFont('Arial','B','14');
		$pdf->cell(0,0,'',1,1,0);
		$pdf->Cell(0,20,$row['patient_fullname'],0,1,2);
		$pdf->SetFont('Arial','','12');
		$pdf->Cell(0,-10,$row['patient_fulladdress'],0,1,2);
		$pdf->Cell(0,20,$row['patient_mobileno'],0,1,2);
			$convert = new DateTime($row['patient_birthdate']); 
              	$date = $convert->format('M d, Y');             
		$pdf->Cell(0,-10,$date,0,1,2);
		$pdf->Cell(0,20,$row['patient_citizenship'],0,1,2);
		$pdf->Cell(0,-10,$row['patient_gender'],0,1,2);
		$pdf->Cell(0,20,$row['patient_civilstatus'],0,1,2);
		$pdf->Cell(0,-10,$row['patient_occupation'],0,1,2);
		$pdf->Cell(0,15,'',0,1,0);
		$pdf->Cell(0,0,'',1,1,0);

		$pdf->Output();
	}
}

?>