<?php
  $active = $this->getAction();
?>

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title><?php echo (isset($this->page_title) ? $this->page_title : 'Home') ?></title>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
  
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>  

  <!-- Custom fonts for this template-->
  <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="/css/sb-admin-2.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
  <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script type="text/javascript">

window.onload = function () {
  var chart = new CanvasJS.Chart("chartContainer", {
   
    data: [              
    {
      
      type: "column",
      dataPoints: [
        {
         label: "No. of Drugs",  
         y:
         <?php
            $totaDrugs = $this->view_data['dataRecords2'];
                      echo $totaDrugs[0][0];
         ?>  
        },
        {
         label: "No. of Stocks", 
         y: 
         <?php
            $totalStocks = $this->view_data['dataRecords3'];
                      echo $totalStocks[0][0];
         ?>  
        },
        {
         label: "Transactions", 
          y: 
          <?php
            $totaTransactions = $this->view_data['dataRecords4'];
                      echo $totaTransactions[0][0];
          ?>
        },
        { 
          label: "No. of Payments",  
          y: 
          <?php
            $totalPayments = $this->view_data['dataRecords5'];
                      echo $totalPayments[0][0];
          ?>  
        }
      ]
    }
    ]
  });
  chart.render();
}
</script>
  
</head>
